POST http://localhost:7071/api/NewComment HTTP/1.1
content-type: application/json

{
    "captchaToken":"superToken",
    "name": "sample",
    "postUrl": "post2",
    "authorName": "Heinz",
    "text": "I would like to add that you can also use this tool to delete all your files. But when will you write another post?",
    "createdTimestampUtc": "2018-10-04T06:02:34.359Z"
}

POST http://localhost:7071/api/NewComment HTTP/1.1
content-type: application/json

{
    "captchaToken":"superToken",
    "name": "sample",
    "postUrl": "post2",
    "authorName": "Heinz",
    "text": "Your post is freaking lame. I really don't like your writing style.",
    "createdTimestampUtc": "2018-10-04T06:02:34.359Z"
}

PUT http://localhost:7071/api/ApplyModeration?key=eyJQYXJ0aXRpb25LZXkiOiJwb3N0MiIsIlJvd0tleSI6ImE4ODNkOTViLTIyZTQtNDIwYi1iNjYyLTUwOTVjYzk5OWRhOCIsInVuYXV0aGVudGljYXRlZE1vZGVyYXRpb25Ub2tlbiI6ImJkMDgwNTNjLWRlMDgtNDgyZi1hMDdjLTVlNzJjOTBhN2UzMiJ9 HTTP/1.1
content-type: application/json

{
    "accepted":true
}

GET http://localhost:7071/api/GetComments?postUrl=post2 HTTP/1.1

POST https://adw1blogcomments.azurewebsites.net/api/NewComment HTTP/1.1
content-type: application/json

{
    "captchaToken":"superToken",
    "name": "sample",
    "postUrl": "post2",
    "authorName": "karl",
    "text": "toller kommentar"
}

GET https://adw1blogcomments.azurewebsites.net/api/GetComments?postUrl=post2 HTTP/1.1


POST https://westeurope.api.cognitive.microsoft.com/text/analytics/v2.0/sentiment/ HTTP/1.1
Content-Type: application/json
Ocp-Apim-Subscription-Key: ****

{
   "documents": [
    {
      "language": "en",
      "id": "1",
      "text": "Hello world. This is some input text that I love."
    }
  ]
}

